const SUCCESS = 'SUCCESS';
const FAILURE = 'FAILURE';
const USER_NOT_FOUND = 'USER NOT FOUND';
const COMPANY_NOT_FOUND = 'COMPANY NOT FOUND'
const UNIVERSITY_NOT_FOUND = 'UNIVERSITY NOT FOUND'
const USER_ALEADY_EXISTS = 'USER ALREADY EXISTS';
const INVALID_PASSWORD = 'INVALID PASSWORD';
const LOGIN_SUCCESSFUL = 'LOGIN SUCCESSFUL';
const REGISTRATION_SUCCESSFUL = 'REGISTRATION_SUCCESSFUL';
const FILL_ALL_DETAILS = 'PLEASE FILL ALL DETAILS';
const SERVER_SIDE_ERROR = 'SERVER SIDE ERROR';
const UNAUTHORIZED_USER = 'UNAUTHORIZED USER';
const DATA_FETCHED = 'DATA FETCHED';
const USER_ALREADY_FOLLOWED = 'USER ALREADY FOLLOWED'
const USER_FOLLOWED = 'USER FOLLOWED'
const USER_UNFOLLOWED = 'USER UNFOLLOWED'
const USER_NOT_FOLLOWED = 'USER NOT FOLLOWED'
const ALL_FOLLOWERS = 'ALL FOLLOWERS'
const ALL_FOLLOWING = 'ALL FOLLOWING'
const NOTI_TOKEN_ADDED = 'NOTIFICATION TOKEN ADDED'
// For Connections
const REQUEST_SENT = 'REQUEST SENT';
const UNSEND_REQUEST = 'REQUEST UNSEND'
const REQUEST_ACCEPTED = 'REQUEST ACCEPTED'
const REQUEST_REJECTED  = 'REQUEST REJECTED'
const ALL_CONNECTIONS_REQUESTS = 'ALL CONNECTIONS REQUESTS'
const REQUEST_NOT_FOUND = 'REQUEST NOT FOUND'
const USER_NOT_CONNECTED = 'USER NOT CONNECTED'
const ALL_CONNECTIONS = 'ALL CONNECTIONS'
const USER_DISCONNECTED = 'USER DISCONNECTED'
// For Messages
const USER_ALREADY_ONLINE = 'USER ALREADY ONLINE'
const USER_ADDED_TO_ONLINE_LIST = 'USER ADDED TO ONLINE LIST'
const USER_REMOVED_FROM_ONLNE_LIST = 'USER REMOVED FROM ONLINE LIST'
const USER_NOT_FOUND_IN_ONLINE_LIST = 'USER NOT FOUND IN ONLINE LIST'
const NEW_MESSAGE = 'NEW MESSAGE'
const MESSAGE_SUCCESSFULLY_SENT_WHEN_ONLINE = 'MESSAGE SUCCESSFULLY SENT WHEN ONLINE'
const MESSAGE_SUCCESSFULLY_SENT_FOR_FUTURE = 'MESSAGE_SUCCESSFULLY_SENT_FOR_FUTURE'
const ALL_MESSAGES = 'ALL MESSAGES'
const ALL_CONVERSATIONS = 'ALL CONVERSATIONS'
const USER_OFFLINE = 'USER OFFLINE'
const USER_ONLINE = 'USER ONLINE'
// For Posts
const COMMENT = 'COMMENT'
const POST = 'POST'
const POSTED = 'POSTED'
const POSTADDED = 'POST ADDED'
const COMMENTED = 'COMMENTED'
const SINGLE_POST = 'SINGLE POST'
const LIKED = 'LIKED'
const TAGGED = 'TAGGED'
const FEED = 'FEED'
const ALL_USER_NAMES = 'ALL USER NAMES'
const NEW_FEED = 'NEW FEED'
// For Companies
const COMPANY_ALREADY_EXISTS = "COMPANY ALREADY EXISTS"

// For Universities
const UNIVERSITY_ALREADY_EXISTS = "UNIVERSITY ALREADY EXISTS"

// Users Avalilable on the platform
const STUDENTS = "STUDENTS"
const PROFESSIONAL_USERS = "PROFESSIONAL USERS"
const RESEARCH_SCHOLARS = "RESEARCH SCHOLARS"
const PROFESSORS = "PROFESSORS"

export {
    SUCCESS,
    FAILURE,
    USER_NOT_FOUND,
    INVALID_PASSWORD,
    LOGIN_SUCCESSFUL,
    REGISTRATION_SUCCESSFUL,
    FILL_ALL_DETAILS,
    USER_ALEADY_EXISTS,
    SERVER_SIDE_ERROR,
    UNAUTHORIZED_USER,
    DATA_FETCHED,
    USER_ALREADY_FOLLOWED,
    USER_FOLLOWED,
    ALL_FOLLOWERS,
    ALL_FOLLOWING,
    USER_UNFOLLOWED,
    USER_NOT_FOLLOWED,
    REQUEST_SENT,
    UNSEND_REQUEST,
    REQUEST_ACCEPTED,
    REQUEST_REJECTED,
    ALL_CONNECTIONS_REQUESTS,
    REQUEST_NOT_FOUND,
    USER_NOT_CONNECTED,
    ALL_CONNECTIONS,
    USER_DISCONNECTED,
    USER_ALREADY_ONLINE,
    USER_ADDED_TO_ONLINE_LIST,
    USER_REMOVED_FROM_ONLNE_LIST,
    USER_NOT_FOUND_IN_ONLINE_LIST,
    NEW_MESSAGE,
    MESSAGE_SUCCESSFULLY_SENT_FOR_FUTURE,
    MESSAGE_SUCCESSFULLY_SENT_WHEN_ONLINE,
    ALL_MESSAGES,
    ALL_CONVERSATIONS,
    USER_ONLINE,
    USER_OFFLINE,
    COMMENT,
    POST,
    POSTED,
    COMMENTED,
    SINGLE_POST,
    POSTADDED,
    NOTI_TOKEN_ADDED,
    LIKED,
    TAGGED,
    FEED,
    ALL_USER_NAMES,
    COMPANY_ALREADY_EXISTS,
    UNIVERSITY_ALREADY_EXISTS,
    STUDENTS,
    PROFESSIONAL_USERS,
    PROFESSORS,
    RESEARCH_SCHOLARS,
    COMPANY_NOT_FOUND,
    UNIVERSITY_NOT_FOUND,
    NEW_FEED
}