const SUCCESS = 'SUCCESS';
const FAILURE = 'FAILURE';
const USER_NOT_FOUND = 'USER NOT FOUND';
const USER_ALEADY_EXISTS = 'USER ALREADY EXISTS';
const INVALID_PASSWORD = 'INVALID PASSWORD';
const LOGIN_SUCCESSFUL = 'LOGIN SUCCESSFUL';
const REGISTRATION_SUCCESSFUL = 'REGISTRATION_SUCCESSFUL';
const FILL_ALL_DETAILS = 'PLEASE FILL ALL DETAILS';
const SERVER_SIDE_ERROR = 'SERVER SIDE ERROR';
const UNAUTHORIZED_USER = 'UNAUTHORIZED USER';
const DATA_FETCHED = 'DATA FETCHED';
const USER_ALREADY_FOLLOWED = 'USER ALREADY FOLLOWED'
const USER_FOLLOWED = 'USER FOLLOWED'
const USER_UNFOLLOWED = 'USER UNFOLLOWED'
const USER_NOT_FOLLOWED = 'USER NOT FOLLOWED'
const ALL_FOLLOWERS = 'ALL FOLLOWERS'
const ALL_FOLLOWING = 'ALL FOLLOWING'
export {
    SUCCESS,
    FAILURE,
    USER_NOT_FOUND,
    INVALID_PASSWORD,
    LOGIN_SUCCESSFUL,
    REGISTRATION_SUCCESSFUL,
    FILL_ALL_DETAILS,
    USER_ALEADY_EXISTS,
    SERVER_SIDE_ERROR,
    UNAUTHORIZED_USER,
    DATA_FETCHED,
    USER_ALREADY_FOLLOWED,
    USER_FOLLOWED,
    ALL_FOLLOWERS,
    ALL_FOLLOWING,
    USER_UNFOLLOWED,
    USER_NOT_FOLLOWED
}