const SUCCESS = 'SUCCESS';
const FAILURE = 'FAILURE';
const USER_NOT_FOUND = 'USER NOT FOUND';
const USER_ALEADY_EXISTS = 'USER ALREADY EXISTS';
const INVALID_PASSWORD = 'INVALID PASSWORD';
const LOGIN_SUCCESSFUL = 'LOGIN SUCCESSFUL';
const REGISTRATION_SUCCESSFUL = 'REGISTRATION_SUCCESSFUL';
const FILL_ALL_DETAILS = 'PLEASE FILL ALL DETAILS';
const SERVER_SIDE_ERROR = 'SERVER SIDE ERROR';
const UNAUTHORIZED_USER = 'UNAUTHORIZED USER';
const DATA_FETCHED = 'DATA FETCHED';

export {
    SUCCESS,
    FAILURE,
    USER_NOT_FOUND,
    INVALID_PASSWORD,
    LOGIN_SUCCESSFUL,
    REGISTRATION_SUCCESSFUL,
    FILL_ALL_DETAILS,
    USER_ALEADY_EXISTS,
    SERVER_SIDE_ERROR,
    UNAUTHORIZED_USER,
    DATA_FETCHED
}